name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ "Debug", "Release" ]

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{ matrix.configuration }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SCGL-${{ matrix.configuration }}
        path: ${{ matrix.configuration }}/SCGL.dll
